/**
 * ACTION TYPES
 */
export const GET_USER = 'GET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const GET_SOUND = 'GET_SOUND';
export const GET_SAVED_SOUND = 'GET_SAVED_SOUND';
export const UPDATE_SOUND = 'UPDATE_SOUND';
export const UPDATE_SOUND_ERROR = 'UPDATE_SOUND_ERROR';
export const RESET_SOUND = 'RESET_SOUND';

export const SAVE_LOOP = 'SAVE_LOOP';
export const GET_LOOPS = 'GET_LOOPS';
export const GET_ONE_LOOP = 'GET_ONE_LOOP';
export const CREATE_NEW_LOOP = 'CREATE_NEW_LOOP';
export const DELETE_LOOP = 'DELETE_LOOP';
export const SAVED_FALSE = 'SAVED_FALSE';
export const CLEAR_LOOPS = 'CLEAR_LOOPS';

export const UPDATE_SEQUENCES = 'UPDATE_SEQUENCES';
export const UPDATE_SEQUENCES_ERROR = 'UPDATE_SEQUENCES_ERROR';
export const UPDATE_ONE_SEQUENCE = 'UPDATE_ONE_SEQUENCE';
export const UPDATE_ONE_SEQUENCE_ERROR = 'UPDATE_ONE_SEQUENCE_ERROR';

export const UPDATE_TEMPO = 'UPDATE_TEMPO';
export const UPDATE_TEMPO_ERROR = 'UPDATE_TEMPO_ERROR';
